---
sudo: required
language: objective-c
# 10.11 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode7.3

install:
  # Install pip
  - sudo easy_install pip

  # Install Ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Install dependencies
  - ansible-galaxy install -r requirements.yml -p ..

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml --syntax-check

  # Check that playbook runs without errors
  - ansible-playbook tests/test.yml

  # Test idempotence
  - idempotence=$(mktemp)
  - ansible-playbook tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
