# frozen_string_literal: true
source 'https://rubygems.org'

gem 'gollum', git: 'https://github.com/gollum/gollum'
gem 'gollum-auth', '~> 0.6'
gem 'gollum-rugged_adapter', '~> 0.4'
gem 'github-markdown'
gem 'puma'
